version: '3.8'
services:
  server:
    image: 'node:16-alpine3.15'
    network_mode: host
    working_dir: /app
    container_name: server
    restart: unless-stopped
    volumes:
      - './:/app'
    command: sh -c "npm i && npm run start:server"
  client:
    image: 'node:16-alpine3.15'
    network_mode: host
    working_dir: /app
    container_name: client
    restart: "no"
    volumes:
      - './:/app'
    command: sh -c "sleep 5 && npm i && npm run start:client"
    depends_on:
      - server